# 基础配置
server:
   port:  8082

# 数据源配置
spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://10.66.2.39:3306/messageservice?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: setpay@123
     type: com.alibaba.druid.pool.DruidDataSource
     filters: stat
     maxActive: 100
     initialSize: 5
     maxWait: 8000
     minIdle: 5
     #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     #配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 1
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 300
     verifyServerCertificate: false
# ActiveMQ 配置
  activemq:
    broker-url: failover:(tcp://10.66.140.33:61616)
    user: admin
    password: admin
    useAsyncSend: true
    alwaysSessionAsync: true
    dispatchAsync: true
    pool:
      enabled:  true
      max-connections: 100
      expiry-timeout: 10000
      idle-timeout: 30000

# Mybatis 配置
mybatis:
  typeAliasesPackage: cn.expopay.messageServer.model
  mapperLocations: classpath:mapper/*.xml

# 日志级别
logging:
  config: classpath:config/logback/logback-spring.xml


