# 基础配置
server:
   port:  8082

# 数据源配置
spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/messageservice?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: root
     type: com.alibaba.druid.pool.DruidDataSource
     filters: stat
     maxActive: 100
     initialSize: 5
     maxWait: 8000
     minIdle: 5
     #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     #配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 1
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxOpenPreparedStatements: 300
     verifyServerCertificate: false
# ActiveMQ 配置
  activemq:
      broker-url: tcp://192.168.88.128:61616
      user: admin
      password: admin
      useAsyncSend: true
      alwaysSessionAsync: true
      dispatchAsync: true
      pool:
        enabled:  true
        max-connections: 100
        expiry-timeout: 10000
        idle-timeout: 30000

# Mybatis 配置
mybatis:
  typeAliasesPackage: cn.expopay.messageServer.model
  mapperLocations: classpath:mapper/*.xml

# 日志级别
logging:
  config: classpath:config/logback/logback-spring.xml

# 接口配置
messageContent:
  send:
    sendMessageTotalNum: 10
    sendMessageTotalBackNum: 10
    sendMessageKeyIsNull: KeyVersion 参数为Null 或 空字符串
    sendMessageSucess: 请求消息服务系统：成功
    sendMessageBackSignFail: 请求消息服务系统：返回加签失败
  back:
    backMessageSignFail: 消息服务系统：回复加签失败
    backMessageKeyVersion: 消息服务系统：回复消息失败，keyVersion版本是
    backMessageFromSenderSignatureFailStr: 消息中间件系统：接收Sender返回信息验签失败
  generalState:
    generalStateOne: 1
    generalStateTwo: 2
    generalStateThree: 3
    generalStateFour: 4
  http:
    connectionRequestTimeout: 1000
    socketTimeout: 1000
    connectTimeout: 1000
    httpCodeSucess: 200
    httpCodeFail: 500
  notExecut:
    httpCodeUnMediaType: 415
    httpSendRequestParameterError: 10001
    httpSendRequestParameterErrorStr: HttpManagerClient sendRequest parameter is error
    httpSendRequestTypeError: 10002
    httpSendRequestTypeErrorStr: HttpManagerClient sendRequest parameter requestMode is error NotMatch RequestType
    httpBackRequestParameterError: 10003
    backMessageFromSenderSignatureError: 10004
    backMessageFromSenderResponseNotJSON: 10005
    backMessageFromSenderHttpEntityIsNull: 10006
    sendMessageSignatureFail: 10007
    sendMessageSignatureFailStr: 请求消息服务系统：验签失败
    sendMessageKeyVersionIsError: 10008
    sendMessageKeyVersionIsErrorStr: keyVersion 版本号异常，没有与之对应的版本号，请检查核对
    returnSignParamterLastErrorStr: 返回加签：keyVersion 版本号异常，没有与之对应的版本号，请检查核对